(PCP-732) Refine logging in broker
This patch updates the log levels of the logged messages according to
the following definition:
ERROR: abnormal failure to startup, establish a connection, or deliver
       a message
WARNING: authorization or authentication failure, or failure to process
         a message
INFO: change in service or connections (connect/disconnect)
DEBUG: sending or responding to messages with identifying information
       (but not content), completing state transitions (namely those logged
       at INFO)
TRACE: receiving messages with full contents, full contents of responses